import { TerminalLine, Section, SectionId } from '@/types';
import { ASCII_LOGO, ASCII_DIVIDER, ASCII_THIN_DIVIDER, ASCII_ZK, ASCII_ARCHITECTURE, ASCII_STACK } from './ascii-art';

function line(type: TerminalLine['type'], content: string, color?: string): TerminalLine {
  return { id: Math.random().toString(36).slice(2), type, content, color };
}

function sys(content: string) { return line('system', content); }
function out(content: string, color?: string) { return line('output', content, color); }
function info(content: string) { return line('info', content); }
function ascii(content: string) { return line('ascii', content); }

export const sections: Section[] = [
  {
    id: 'home',
    path: '/home',
    title: 'Welcome to ZKProofport',
    lines: [
      ascii(ASCII_LOGO),
      out(''),
      out('  Privacy Infrastructure for the Next Generation of dApps', '#06b6d4'),
      out(''),
      out('  > "Prove who you are without revealing who you are"', '#7c3aed'),
      out(''),
      out('  ZKProofport is a complete zero-knowledge proof pipeline:'),
      out('  from Noir circuits to mobile proof generation to on-chain verification.'),
      out(''),
      info(ASCII_THIN_DIVIDER),
      out(''),
      out('  ✦ Noir Circuits     — Write privacy-preserving programs'),
      out('  ✦ Mobile Proving    — Generate ZK proofs on iOS & Android'),
      out('  ✦ On-Chain Verify   — Trustless verification on Base L2'),
      out('  ✦ SDK + Relay       — Integrate in minutes, not months'),
      out('  ✦ AI Agent          — Chat, MCP, A2A — prove with natural language'),
      out(''),
      info('  Press [Enter] to continue or type a section number...'),
    ],
  },
  {
    id: 'about',
    path: '/about',
    title: 'What is ZKProofport?',
    lines: [
      ascii(ASCII_ZK),
      out(''),
      sys('  THE PROBLEM'),
      out('  ───────────'),
      out('  Web3 faces a paradox: compliance requires identity,'),
      out('  but blockchain is designed for pseudonymity.'),
      out('  KYC providers see your data. On-chain is forever.'),
      out(''),
      sys('  THE SOLUTION'),
      out('  ────────────'),
      out('  ZKProofport lets users prove facts about themselves'),
      out('  (age, KYC status, country) without revealing the underlying data.'),
      out(''),
      sys('  BUSINESS MODEL'),
      out('  ──────────────'),
      out('  ┌──────────────┬──────────────────────────────┐'),
      out('  │ Free Tier    │ 10 verifications/month        │'),
      out('  │ Credit       │ Pay-per-use, $0.05/proof      │'),
      out('  │ Plan 1       │ 1,000 proofs/month            │'),
      out('  │ Plan 2       │ 10,000 proofs/month           │'),
      out('  └──────────────┴──────────────────────────────┘'),
      out(''),
      sys('  STATUS'),
      out('  ──────'),
      out('  ● Live on Base Sepolia (testnet)', '#00ff41'),
      out('  ● AI Agent (staging) — proveragent.eth', '#06b6d4'),
      out('  ● 2 circuits deployed'),
      out('  ● ERC-8004 TEE Agent with x402 payments'),
      out('  ● Web + Telegram + MCP interfaces'),
      out(''),
    ],
  },
  {
    id: 'tech',
    path: '/tech',
    title: 'Technology Stack',
    lines: [
      sys('  TECHNOLOGY STACK'),
      out('  ════════════════'),
      out(''),
      out('  The ZKProofport stack, from top to bottom:'),
      out(''),
      ascii(ASCII_STACK),
      out(''),
      sys('  COMPILE → PROVE → VERIFY PIPELINE'),
      out('  ──────────────────────────────────'),
      out('  1. Write circuit in Noir language          (*.nr)'),
      out('  2. Compile with nargo                      (circuit.json)'),
      out('  3. Generate verification key with bb       (vk)'),
      out('  4. Create Solidity verifier with bb        (Verifier.sol)'),
      out('  5. Deploy verifier to Base L2              (on-chain)'),
      out('  6. Generate proofs on mobile via mopro     (256 bytes)'),
      out('  7. Verify on-chain in ~200k gas            (trustless)'),
      out(''),
      sys('  KEY METRICS'),
      out('  ───────────'),
      out('  Proof size:        256 bytes'),
      out('  Verification gas:  ~200,000'),
      out('  Prove time:        2-4 seconds (mobile)'),
      out('  Circuit language:  Noir 1.0.0-beta.8'),
      out('  Proving backend:   Barretenberg (UltraPlonk)'),
      out('  AI Agent:          proveragent.eth (TEE-attested)'),
      out('  LLM Integration:   Gemini 2.5 + OpenAI (multi-provider)'),
      out('  Payment:           x402 Protocol ($0.10 USDC/proof)'),
      out(''),
    ],
  },
  {
    id: 'architecture',
    path: '/architecture',
    title: 'System Architecture',
    lines: [
      sys('  SYSTEM ARCHITECTURE'),
      out('  ═══════════════════'),
      out(''),
      ascii(ASCII_ARCHITECTURE),
      out(''),
      sys('  DATA FLOW'),
      out('  ─────────'),
      out('  1. dApp calls SDK → creates proof request'),
      out('  2. Relay forwards to user\'s mobile app'),
      out('  3. Mobile app generates ZK proof (2-4s)'),
      out('  4. Proof sent back through relay'),
      out('  5. SDK submits proof on-chain'),
      out('  6. Solidity verifier confirms validity'),
      out(''),
      sys('  SYBIL RESISTANCE'),
      out('  ─────────────────'),
      out('  Nullifier = keccak256(keccak256(address + signalHash) + scope)'),
      out('  → One proof per wallet per circuit'),
      out('  → Cannot reuse proofs across dApps'),
      out('  → Privacy preserved: no link between proofs'),
      out(''),
    ],
  },
  {
    id: 'demos',
    path: '/demos',
    title: 'Live Demonstrations',
    lines: [
      sys('  LIVE DEMONSTRATIONS'),
      out('  ═══════════════════'),
      out(''),
      out('  Available interfaces:'),
      out(''),
      out('  [1] Web Demo    — demo.zkproofport.app (staging)'),
      out('  [2] AI Chat     — Chat tab on this page'),
      out('  [3] MCP Develop — Develop tab on this page'),
      out('  [4] Telegram    — @proveragent_bot'),
      out(''),
      info('  Switch tabs above to try Develop or Chat mode.'),
      out(''),
    ],
  },
  {
    id: 'usecases',
    path: '/usecases',
    title: 'Use Cases & Applications',
    lines: [
      sys('  USE CASES & APPLICATIONS'),
      out('  ════════════════════════'),
      out(''),
      out('  1. COMPLIANT DEFI', '#06b6d4'),
      out('     KYC verification without doxxing. Users prove'),
      out('     Coinbase identity verification to access DeFi protocols.'),
      out(''),
      out('  2. GEOGRAPHIC RESTRICTIONS', '#06b6d4'),
      out('     Prove you\'re in an allowed jurisdiction without'),
      out('     revealing your exact location or nationality.'),
      out(''),
      out('  3. AGE VERIFICATION', '#06b6d4'),
      out('     Prove you\'re 18+ for restricted content'),
      out('     without sharing your date of birth.'),
      out(''),
      out('  4. DAO GOVERNANCE', '#06b6d4'),
      out('     One-person-one-vote via nullifiers.'),
      out('     Prevents Sybil attacks while preserving voter privacy.'),
      out(''),
      out('  5. ZKPSWAP DEX', '#06b6d4'),
      out('     A compliant decentralized exchange where traders'),
      out('     prove KYC status without revealing identity to counterparties.'),
      out(''),
    ],
  },
  {
    id: 'stats',
    path: '/stats',
    title: 'Network Statistics',
    lines: [
      sys('  ZKPROOFPORT NETWORK STATS (brutally honest edition)'),
      out('  ════════════════════════════════════════════════════'),
      out(''),
      out('  Proofs Generated:      42  (and counting... slowly)'),
      out('  On-Chain Verified:      37  (5 got lost in the mempool)'),
      out('  Unique Wallets:          3  (it\'s us, mostly)'),
      out('  AI Agent Conversations:  7  (the bot talks to itself sometimes)'),
      out('  Circuits Deployed:       2  (quality over quantity)'),
      out('  Avg Proof Time:       ~90s  (grab a coffee)'),
      out('  Network:        Base Sepolia (testnet, we\'re not THAT brave)'),
      out(''),
      out('  [██░░░░░░░░] 12% to world domination', '#06b6d4'),
      out(''),
      info('  * Stats are real. Dreams are bigger.'),
      out('  * Projected 2027: 1M proofs/day (we did the math on a napkin)'),
      out(''),
    ],
  },
  {
    id: 'team',
    path: '/team',
    title: 'About Us',
    lines: [
      sys('  ABOUT US'),
      out('  ════════'),
      out(''),
      out('  ZKProofport is built by a team passionate about'),
      out('  privacy-preserving infrastructure for Web3.'),
      out(''),
      sys('  POWERED BY'),
      out('  ──────────'),
      out('  Aztec Network — Creator of Noir and Barretenberg'),
      out('                  Privacy-first L2, backed by Paradigm & Vitalik Buterin'),
      out(''),
      sys('  INCUBATED BY'),
      out('  ────────────'),
      out('  Base (Coinbase L2) — Incubation program in progress'),
      out(''),
      sys('  OPEN SOURCE'),
      out('  ───────────'),
      out('  Our SDK, circuits, and tooling are open source.'),
      out('  → github.com/zkproofport'),
      out(''),
    ],
  },
  {
    id: 'contact',
    path: '/contact',
    title: 'Get in Touch',
    lines: [
      sys('  GET IN TOUCH'),
      out('  ════════════'),
      out(''),
      out('  We\'d love to hear from you.'),
      out(''),
      out('  GitHub:      github.com/zkproofport'),
      out('  Dashboard:   stg-dashboard.zkproofport.app'),
      out('  Demo:        stg-demo.zkproofport.app'),
      out('  AI Agent:    stg-ai.zkproofport.app'),
      out('  Telegram:    @proveragent_bot'),
      out(''),
      sys('  INTERESTED IN INTEGRATING?'),
      out('  ──────────────────────────'),
      out('  1. Sign up at dashboard.zkproofport.app'),
      out('  2. Create a dApp and get your API key'),
      out('  3. Install the SDK: npm install @proofport/sdk'),
      out('  4. Follow the integration guide'),
      out(''),
      sys(''),
      sys('[system] vibe-coded by zkproofport team x Claude Opus 4.6 x proveragent.eth'),
      out(''),
    ],
  },
];

export function getSectionByIndex(index: number): Section | undefined {
  return sections[index];
}

export function getSectionById(id: SectionId): Section | undefined {
  return sections.find(s => s.id === id);
}

export const sectionMenuItems = sections.map((s, i) => ({
  index: i,
  id: s.id,
  path: s.path,
  title: s.title,
}));
