import { TerminalLine, Section, SectionId } from '@/types';
import { ASCII_LOGO, ASCII_DIVIDER, ASCII_THIN_DIVIDER, ASCII_ZK, ASCII_ARCHITECTURE, ASCII_STACK } from './ascii-art';

function line(type: TerminalLine['type'], content: string, color?: string): TerminalLine {
  return { id: Math.random().toString(36).slice(2), type, content, color };
}

function sys(content: string) { return line('system', content); }
function out(content: string, color?: string) { return line('output', content, color); }
function info(content: string) { return line('info', content); }
function ascii(content: string) { return line('ascii', content); }

export const sections: Section[] = [
  {
    id: 'home',
    path: '/home',
    title: 'Welcome to ZKProofport',
    lines: [
      ascii(ASCII_LOGO),
      out(''),
      out('  Privacy Infrastructure for the Next Generation of dApps', '#06b6d4'),
      out(''),
      out('  > "Prove who you are without revealing who you are"', '#7c3aed'),
      out(''),
      out('  ZKProofport is a complete zero-knowledge proof pipeline:'),
      out('  from Noir circuits to mobile proof generation to on-chain verification.'),
      out(''),
      info(ASCII_THIN_DIVIDER),
      out(''),
      out('  ✦ Noir Circuits     — Write privacy-preserving programs'),
      out('  ✦ Mobile Proving    — Generate ZK proofs on iOS & Android'),
      out('  ✦ On-Chain Verify   — Trustless verification on Base L2'),
      out('  ✦ SDK + Relay       — Integrate in minutes, not months'),
      out(''),
      info('  Press [Enter] to continue or type a section number...'),
    ],
  },
  {
    id: 'about',
    path: '/about',
    title: 'What is ZKProofport?',
    lines: [
      ascii(ASCII_ZK),
      out(''),
      sys('  THE PROBLEM'),
      out('  ───────────'),
      out('  Web3 faces a paradox: compliance requires identity,'),
      out('  but blockchain is designed for pseudonymity.'),
      out('  KYC providers see your data. On-chain is forever.'),
      out(''),
      sys('  THE SOLUTION'),
      out('  ────────────'),
      out('  ZKProofport lets users prove facts about themselves'),
      out('  (age, KYC status, country) without revealing the underlying data.'),
      out(''),
      sys('  BUSINESS MODEL'),
      out('  ──────────────'),
      out('  ┌──────────────┬──────────────────────────────┐'),
      out('  │ Free Tier    │ 10 verifications/month        │'),
      out('  │ Credit       │ Pay-per-use, $0.05/proof      │'),
      out('  │ Plan 1       │ 1,000 proofs/month            │'),
      out('  │ Plan 2       │ 10,000 proofs/month           │'),
      out('  └──────────────┴──────────────────────────────┘'),
      out(''),
      sys('  STATUS'),
      out('  ──────'),
      out('  ● Live on Base Sepolia (testnet)', '#00ff41'),
      out('  ● 2 circuits in production'),
      out('  ● SDK available on npm'),
      out('  ● Dashboard: dashboard.zkproofport.app'),
      out(''),
    ],
  },
  {
    id: 'tech',
    path: '/tech',
    title: 'Technology Stack',
    lines: [
      sys('  TECHNOLOGY STACK'),
      out('  ════════════════'),
      out(''),
      out('  The ZKProofport stack, from top to bottom:'),
      out(''),
      ascii(ASCII_STACK),
      out(''),
      sys('  COMPILE → PROVE → VERIFY PIPELINE'),
      out('  ──────────────────────────────────'),
      out('  1. Write circuit in Noir language          (*.nr)'),
      out('  2. Compile with nargo                      (circuit.json)'),
      out('  3. Generate verification key with bb       (vk)'),
      out('  4. Create Solidity verifier with bb        (Verifier.sol)'),
      out('  5. Deploy verifier to Base L2              (on-chain)'),
      out('  6. Generate proofs on mobile via mopro     (256 bytes)'),
      out('  7. Verify on-chain in ~200k gas            (trustless)'),
      out(''),
      sys('  KEY METRICS'),
      out('  ───────────'),
      out('  Proof size:        256 bytes'),
      out('  Verification gas:  ~200,000'),
      out('  Prove time:        2-4 seconds (mobile)'),
      out('  Circuit language:  Noir 1.0.0-beta.8'),
      out('  Proving backend:   Barretenberg (UltraPlonk)'),
      out(''),
    ],
  },
  {
    id: 'architecture',
    path: '/architecture',
    title: 'System Architecture',
    lines: [
      sys('  SYSTEM ARCHITECTURE'),
      out('  ═══════════════════'),
      out(''),
      ascii(ASCII_ARCHITECTURE),
      out(''),
      sys('  DATA FLOW'),
      out('  ─────────'),
      out('  1. dApp calls SDK → creates proof request'),
      out('  2. Relay forwards to user\'s mobile app'),
      out('  3. Mobile app generates ZK proof (2-4s)'),
      out('  4. Proof sent back through relay'),
      out('  5. SDK submits proof on-chain'),
      out('  6. Solidity verifier confirms validity'),
      out(''),
      sys('  SYBIL RESISTANCE'),
      out('  ─────────────────'),
      out('  Nullifier = keccak256(keccak256(address + signalHash) + scope)'),
      out('  → One proof per wallet per circuit'),
      out('  → Cannot reuse proofs across dApps'),
      out('  → Privacy preserved: no link between proofs'),
      out(''),
    ],
  },
  {
    id: 'demos',
    path: '/demos',
    title: 'Live Demonstrations',
    lines: [
      sys('  LIVE DEMONSTRATIONS'),
      out('  ═══════════════════'),
      out(''),
      out('  Available demonstrations:'),
      out(''),
      out('  [1] KYC Verification Flow              (2:30)'),
      out('  [2] Country Attestation                 (1:45)'),
      out('  [3] ZKPSwap — Compliant DEX             (3:00)'),
      out('  [4] SDK Integration Guide               (4:15)'),
      out(''),
      info('  Type a number to learn more, or type /demo to open live demo.'),
      out(''),
      sys('  LIVE DEMO'),
      out('  ─────────'),
      out('  → https://demo.zkproofport.app'),
      out('  Scan QR code with ZKProofport mobile app to try a real proof.'),
      out(''),
    ],
  },
  {
    id: 'usecases',
    path: '/usecases',
    title: 'Use Cases & Applications',
    lines: [
      sys('  USE CASES & APPLICATIONS'),
      out('  ════════════════════════'),
      out(''),
      out('  1. COMPLIANT DEFI', '#06b6d4'),
      out('     KYC verification without doxxing. Users prove'),
      out('     Coinbase identity verification to access DeFi protocols.'),
      out(''),
      out('  2. GEOGRAPHIC RESTRICTIONS', '#06b6d4'),
      out('     Prove you\'re in an allowed jurisdiction without'),
      out('     revealing your exact location or nationality.'),
      out(''),
      out('  3. AGE VERIFICATION', '#06b6d4'),
      out('     Prove you\'re 18+ for restricted content'),
      out('     without sharing your date of birth.'),
      out(''),
      out('  4. DAO GOVERNANCE', '#06b6d4'),
      out('     One-person-one-vote via nullifiers.'),
      out('     Prevents Sybil attacks while preserving voter privacy.'),
      out(''),
      out('  5. ZKPSWAP DEX', '#06b6d4'),
      out('     A compliant decentralized exchange where traders'),
      out('     prove KYC status without revealing identity to counterparties.'),
      out(''),
    ],
  },
  {
    id: 'stats',
    path: '/stats',
    title: 'Network Statistics',
    lines: [
      sys('  ZKPROOFPORT NETWORK STATS'),
      out('  ═════════════════════════'),
      out(''),
      out('  Proofs Generated:    1,247'),
      out('  On-Chain Verified:     892'),
      out('  Unique Wallets:        341'),
      out('  Circuits Deployed:       2'),
      out('  Avg Proof Time:      3.2s'),
      out('  Network:        Base Sepolia'),
      out(''),
      out('  [████████░░] 89.2% verification rate', '#06b6d4'),
      out(''),
      info('  Last updated: Jan 15, 2026'),
      out(''),
      sys('  PROOF LIFECYCLE SIMULATION'),
      out('  ──────────────────────────'),
      out('  [system] Proof request received from dApp'),
      out('  [relay]  Creating proof session... OK', '#06b6d4'),
      out('  [mobile] Downloading circuit (32KB)... done'),
      out('  [mobile] Loading SRS (32MB)... done'),
      out('  [mobile] Generating ZK proof...'),
      out('           witness computation... 0.4s'),
      out('           proving... 2.8s'),
      out('  [relay]  Proof received (256 bytes)', '#06b6d4'),
      out('  [chain]  Submitting to Base Sepolia...'),
      out('  [chain]  Tx: 0x7a3f...8e21', '#7c3aed'),
      out('  [chain]  Verified! Block #18,294,571', '#00ff41'),
      out('  [system] Total time: 4.1s'),
      out(''),
    ],
  },
  {
    id: 'team',
    path: '/team',
    title: 'About Us',
    lines: [
      sys('  ABOUT US'),
      out('  ════════'),
      out(''),
      out('  ZKProofport is built by a team passionate about'),
      out('  privacy-preserving infrastructure for Web3.'),
      out(''),
      sys('  POWERED BY'),
      out('  ──────────'),
      out('  Aztec Network — Creator of Noir and Barretenberg'),
      out('                  Privacy-first L2, backed by Paradigm & Vitalik Buterin'),
      out(''),
      sys('  INCUBATED BY'),
      out('  ────────────'),
      out('  Base (Coinbase L2) — Incubation program in progress'),
      out(''),
      sys('  OPEN SOURCE'),
      out('  ───────────'),
      out('  Our SDK, circuits, and tooling are open source.'),
      out('  → github.com/zkproofport'),
      out(''),
    ],
  },
  {
    id: 'contact',
    path: '/contact',
    title: 'Get in Touch',
    lines: [
      sys('  GET IN TOUCH'),
      out('  ════════════'),
      out(''),
      out('  We\'d love to hear from you.'),
      out(''),
      out('  GitHub:      github.com/zkproofport'),
      out('  Dashboard:   dashboard.zkproofport.app'),
      out('  Demo:        demo.zkproofport.app'),
      out('  SDK Docs:    docs.zkproofport.app'),
      out(''),
      sys('  INTERESTED IN INTEGRATING?'),
      out('  ──────────────────────────'),
      out('  1. Sign up at dashboard.zkproofport.app'),
      out('  2. Create a dApp and get your API key'),
      out('  3. Install the SDK: npm install @proofport/sdk'),
      out('  4. Follow the integration guide'),
      out(''),
      sys(''),
      sys('[system] vibe-coded by zkproofport team x Claude Opus 4.5'),
      out(''),
    ],
  },
];

export function getSectionByIndex(index: number): Section | undefined {
  return sections[index];
}

export function getSectionById(id: SectionId): Section | undefined {
  return sections.find(s => s.id === id);
}

export const sectionMenuItems = sections.map((s, i) => ({
  index: i,
  id: s.id,
  path: s.path,
  title: s.title,
}));
